name: Deploy website to OVH

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build and deploy
        env:
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: ./.workflows/build/package.sh --upload
